### ISSUE TITLE
코드의 의미는 무엇인가요?

### ISSUE THREAD

**Issue by chulhongsung** [yanggochi-warriors/Predict-KBO-OPS#1]
https://github.com/yanggochi-warriors/Predict-KBO-OPS/blob/c574c995499b86f65088ae20630adde53897b7b5/code.R#L41

**Comment by Monster-Moon** [comment]
scale() 함수에 함께 출력되는 'scaled:center'의 attribute를 제거하기 위해 사용했습니다
